# Generated by Django 6.0.7 on 2026-09-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0001_initial"),
        ("tours", "0002_tour_image_tour_join_code_tourmember"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_method", models.CharField(choices=[("cash", "Cash"), ("bank_transfer", "Bank Transfer"), ("jazzcash", "JazzCash"), ("easypaisa", "Easypaisa"), ("other", "Other")], max_length=20)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                ("payer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments_made", to=settings.AUTH_USER_MODEL)),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments_received", to=settings.AUTH_USER_MODEL)),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="settlement_payments", to="tours.tour")),
            ],
            options={
                "verbose_name": "Settlement Payment",
                "verbose_name_plural": "Settlement Payments",
                "ordering": ["-paid_at"],
            },
        ),
    ]
