# Generated by Django 6.0.7 on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reports", "0002_settlementpayment")]

    operations = [
        migrations.AddField(
            model_name="settlementpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
