# Generated by Django 6.0.7 on 2026-09-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_settlementpayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa'), ('raast', 'Raast (manual transfer)'), ('other', 'Other')], max_length=20),
        ),
    ]
